<?php 
 return array (
  'COOKIE_EXPIRE' => '3600',
  'COOKIE_DOMAIN' => '',
  'COOKIE_PATH' => '/',
  'SESSION_PREFIX' => '',
  'SESSION_OPTIONS' => 
  array (
    'domain' => '',
  ),
  'SHOW_ERROR_MSG' => '0',
  'ERROR_MESSAGE' => '您浏览的页面暂时发生了错误！请稍后再试～',
  'ERROR_PAGE' => '',
  'URL_CASE_INSENSITIVE' => true,
  'URL_MODEL' => 0,
  'URL_PATHINFO_DEPR' => '/',
  'URL_HTML_SUFFIX' => '.html',
  'TOKEN_ON' => true,
  'TOKEN_NAME' => '__hash__',
  'TOKEN_TYPE' => 'md5',
  'DEFAULT_MODULE' => 'Manage',
  'DEFAULT_TIMEZONE' => 'PRC',
  'DEFAULT_AJAX_RETURN' => 'JSON',
  'DEFAULT_FILTER' => 'htmlspecialchars',
  'DEFAULT_LANG' => 'zh-cn',
  'DATA_CACHE_TYPE' => 'File',
  'DATA_CACHE_SUBDIR' => '1',
  'LOAD_EXT_FILE' => 'extend',
  'DEFAULT_GROUP' => 'Manage',
);